// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWIr1pOTf9diDIW-A186IOMsUrVLfHowo',
    appId: '1:790861426388:web:6eefac04c7b57d25431541',
    messagingSenderId: '790861426388',
    projectId: 'sic-final-project-14151',
    authDomain: 'sic-final-project-14151.firebaseapp.com',
    databaseURL: 'https://sic-final-project-14151-default-rtdb.firebaseio.com',
    storageBucket: 'sic-final-project-14151.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGwHFoKYtOBqM1aOmbS1pxzPXpiwJkUVI',
    appId: '1:790861426388:android:53231492928c7a1d431541',
    messagingSenderId: '790861426388',
    projectId: 'sic-final-project-14151',
    databaseURL: 'https://sic-final-project-14151-default-rtdb.firebaseio.com',
    storageBucket: 'sic-final-project-14151.appspot.com',
  );

}